# Generated by Django 3.0.4 on 2020-03-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipality_data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orp',
            fields=[
                ('kod', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('spravni_obec_kod', models.CharField(max_length=10)),
                ('vusc_kod', models.CharField(max_length=10)),
                ('plati_od', models.DateTimeField()),
                ('plati_do', models.DateTimeField(blank=True, null=True)),
                ('datum_vzniku', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pou',
            fields=[
                ('kod', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('spravni_obec_kod', models.CharField(max_length=10)),
                ('plati_od', models.DateTimeField()),
                ('plati_do', models.DateTimeField(blank=True, null=True)),
                ('datum_vzniku', models.DateTimeField()),
                ('orp_kod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='municipality_data_app.Orp')),
            ],
        ),
        migrations.DeleteModel(
            name='Obec',
        ),
    ]
