# Generated by Django 2.2.5 on 2020-03-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipality_data_app', '0002_auto_20200319_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obec',
            fields=[
                ('kod', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('status_kod', models.CharField(max_length=5)),
                ('pou_kod', models.CharField(max_length=10)),
                ('okres_kod', models.CharField(max_length=10)),
                ('cleneni_sm_rozsah_kod', models.CharField(blank=True, max_length=30, null=True)),
                ('cleneni_sm_typ_kod', models.CharField(blank=True, max_length=30, null=True)),
                ('plati_od', models.DateTimeField()),
                ('plati_do', models.DateTimeField(blank=True, null=True)),
                ('datum_vzniku', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orp',
            name='spravni_obec_kod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='municipality_data_app.Obec'),
        ),
        migrations.AlterField(
            model_name='pou',
            name='spravni_obec_kod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='municipality_data_app.Obec'),
        ),
    ]
