# Generated by Django 2.2.5 on 2020-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipality_data_app', '0003_auto_20200319_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obec',
            name='kod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
